
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bookshop?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml   #mapper映射xml文件所在路径
  type-aliases-package: com.csu.bookshop.model    #对应实体类路径
  configuration:    #命名驼峰映射
    map-underscore-to-camel-case: true
  #mybatis.config-location=classpath:mybatis-config.xml // 配置文件位置